version: 0.2

phases:
  build:
      commands:
        - composer install
  post_build:
      commands:
        - php -v
        - composer -v
        - php artisan --version
        - php artisan cache:clear
        - php artisan config:clear
artifacts:
  files:
    - '**/*'